"""Increase column lengths for status

Revision ID: 44df815ef0e2
Revises: 5d255d5670fa
Create Date: 2025-02-06 22:27:50.370799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44df815ef0e2'
down_revision = '5d255d5670fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
