"""Added country_name and country_code to Event model

Revision ID: 5d255d5670fa
Revises: 0b3d7a5a08dc
Create Date: 2025-01-28 21:46:21.180803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d255d5670fa'
down_revision = '0b3d7a5a08dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('country_code')
        batch_op.drop_column('country_name')

    # ### end Alembic commands ###
