"""Initial migration

Revision ID: 5e2900d5484b
Revises: 
Create Date: 2025-01-24 17:35:30.980982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2900d5484b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_recognition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('second', sa.Integer(), nullable=False),
    sa.Column('face', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('percent_neutral', sa.Float(), nullable=False),
    sa.Column('percent_happy', sa.Float(), nullable=False),
    sa.Column('percent_angry', sa.Float(), nullable=False),
    sa.Column('percent_sad', sa.Float(), nullable=False),
    sa.Column('percent_fear', sa.Float(), nullable=False),
    sa.Column('percent_surprise', sa.Float(), nullable=False),
    sa.Column('percent_disgust', sa.Float(), nullable=False),
    sa.Column('percent_contempt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_recognition')
    op.drop_table('event')
    # ### end Alembic commands ###
